insert into material_absortancia(superficie, alfa_ini, alfa_fim, beta_ini, beta_fim) values ('Chapa de aluminio (nova e brilhante)', 0.05, 0.05, 0.00, 0.00);
insert into material_absortancia(superficie, alfa_ini, alfa_fim, beta_ini, beta_fim) values ('Chapa de aluminio (oxidada)', 0.15, 0.15, 0.00, 0.00);
insert into material_absortancia(superficie, alfa_ini, alfa_fim, beta_ini, beta_fim) values ('Chapa de aço galvanizada (nova e brilhante)', 0.25, 0.25, 0.00, 0.00);
insert into material_absortancia(superficie, alfa_ini, alfa_fim, beta_ini, beta_fim) values ('Caiação nova', 0.12, 0.15, 0.00, 0.00);
insert into material_absortancia(superficie, alfa_ini, alfa_fim, beta_ini, beta_fim) values ('Concreto aparente', 0.65, 0.80, 0.00, 0.00);
insert into material_absortancia(superficie, alfa_ini, alfa_fim, beta_ini, beta_fim) values ('Telha de barro', 0.75, 0.80, 0.00, 0.00);
insert into material_absortancia(superficie, alfa_ini, alfa_fim, beta_ini, beta_fim) values ('Tijolo aparente', 0.65, 0.80, 0.00, 0.00);
insert into material_absortancia(superficie, alfa_ini, alfa_fim, beta_ini, beta_fim) values ('Reboco claro', 0.30, 0.50, 0.00, 0.00);
insert into material_absortancia(superficie, alfa_ini, alfa_fim, beta_ini, beta_fim) values ('Revestimento asfáltico', 0.85, 0.98, 0.00, 0.00);
insert into material_absortancia(superficie, alfa_ini, alfa_fim, beta_ini, beta_fim) values ('Vidro incolor', 0.00, 0.06, 0.25, 0.00);
insert into material_absortancia(superficie, alfa_ini, alfa_fim, beta_ini, beta_fim) values ('Vidro colorido', 0.00, 0.40, 0.80, 0.00);
insert into material_absortancia(superficie, alfa_ini, alfa_fim, beta_ini, beta_fim) values ('Vidro metalizado', 0.00, 0.35, 0.80, 0.00);